name: ci
on:
  pull_request:
    branches:
      - main
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウトする
        uses: actions/checkout@v4
      - name: Goの環境をセットアップ
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      - name: フォーマットの実行
        run: test -z $(go fmt -l .)
      - name: 静的解析
        run: go vet ./...
      - name: testの実行
        run: go test
      - name: buildの実行
        run: go build .

